name: bemall_promocoes
description: Aplicativo Bemall Promoções
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.2.0
  webview_flutter_wkwebview: ^3.18.4
  permission_handler: ^11.3.0
  url_launcher: ^6.0.20
  mobile_scanner: 6.0.7
  image_picker: ^1.0.7
  sentry_flutter: ^8.0.0
  http: ^1.2.0
  path_provider: ^2.1.0
  camera: ^0.11.1
  shared_preferences: ^2.5.2
  flutter_launcher_icons: ^0.14.3
  image: ^4.1.3
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true
