name: Build iOS App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Permite executar manualmente

jobs:
  build:
    runs-on: macos-latest # Usa uma máquina macOS

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.0"
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: |
          cd ios
          pod install
          cd ..
          flutter build ios --release --no-codesign

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: build/ios/iphoneos
